---
title: "Notes with autocompletion"
subtitle: "Assignment for Coursera Data Science Capstone"
author: "Norihito Nakata"
date: "1/13/2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## About

This is an assginment for [Data Science Capstone](https://www.coursera.org/learn/data-science-project) course in coursera.

I developed ***Notes with autocompletion***, which is an application to create notes/memos easy.
Autocompletion function helps users to type the next word based on their input words.

[Application link](https://norihiton.shinyapps.io/NextWordPrediction)

[Source code](https://github.com/NorihitoN/nextWordPrediction)

## How To Use

- Write your note in the text box at the left side bar.
- During writing a note, the next prediction word appears below the text box in 5sec.
- If you click one of the prediction words, the clicked word will be added to the text box. If not needed, coutinue to write by yourself.
- Click "Post" button to add your note to "Memos" list at the main panel.
- Click "Clear" button to clear all your notes.

## Prediction Model

To predict the next words, three-gram method is used, which is the special case of N-gram method.

- Model Building

Sampled all sentences from blogs. The data are tokenized by **quanteda** library and are converted to a document-feature matrix (`ngrams = 3`).
I used `textstat_frequency` function to create the dataset which has two columns, `3-gram` and `frequency`. I extracted `3-gram` of which `frequency` is above one, and saved as `3gram.csv`.

- Prediction

The prediction function gets input sentence and extracts the last two words, and finds three-gram words from `3gram.csv` which matches the extracted two words. If three-grams are found, the function returns the third word of the three-gram.


## Performance

- Model Performance

The accuracy of this function is not high because the target of upper limit of file size should be less than 100MB. 
I will try to create other dataset by using 5/4 gram to take care of file size and prediction accuracy.
